export const QUERY_KEYS = {
  FECTH_COURSES: 'FECTH_COURSES',
  FETCH_COURSES_USER: 'FETCH_COURSES_USER',
  FETCH_HISTORY: 'FETCH_HISTORY',
  FETCH_LESSON_BY_COURSE: 'FETCH_LESSON_BY_COURSE',
  CREATE_COURSE: 'CREATE_COURSE',
  UPDATE_COURSE: 'UPDATE_COURSE',
} as const;
